baseurl: /multilingual
permalink: pretty
markdown: rdiscount
permalink: /:categories/:title
languages:
  - name: 'English'
    key: 'en'
  - name: 'Español'
    key: 'es'

# Prose settings
prose:
  rooturl: '_posts'
  siteurl: 'http://www.micren.co.uk/multilingual/'
  relativeLinks: 'http://www.micren.co.uk/multilingual/links.jsonp'
  media: 'img'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "meta-title"
        field:
          element: "text"
          label: "Meta Title"
          value: ""
      - name: "meta-description"
        field:
          element: "text"
          label: "Meta Description" 
          value: ""
      - name: "title-short"
        field:
          element: "text"
          label: "Title Short"
          value: ""
      - name: "bite"
        field:
          element: "text"
          label: "Bite"
          value: ""
      - name: "lang"
        field:
          element: "select"
          label: "Select language"
          placeholder: "English"
          options: *languages
          selected: "en"
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
      - name: "seo-keywords"
        field:
          element: "text"
          label: "SEO Keywords"
          value: ""
